### ISSUE TITLE
update doesnt go through

### ISSUE THREAD

**Issue by ac31447** [Freebi85/Dungeons-Dragons-Space-Shuttles#505] opened 2019-11-24 00:05 UTC
Please report the following issues on this Github Issue Tracker:

- Not working / broken recipes 
- Proposals for new recipes or recipes that still need to be balanced.
- Suggestions for missing or additional integrations in machines
- Any problems with quests (description, spelling mistakes, task not recognized etc.)
- For Mod Issues check first official Mod Githubs if it has already been reported and if not report it there!

**Do NOT Report here:**
-Server problems or crashes. Use our helpdesk (tech-support) in our Discord Server to get some help with serverside issues. Discord Link: https://discord.gg/eUajYmK

**Comment by ac31447** [comment] 2019-11-24 00:06
it stops bout halfway through and says Unable to get Addon: Default Options (232131) - File ID: 2624732

**Comment by dierke9** [comment] 2019-11-24 00:07
Twitch problem. Try fully closing twitch and restarting. If that doesnt work then try updating to a new profile.

**Comment by dierke9** [comment] 2019-11-24 00:07
If the problem is still there then join our Discord so we can find the problem

**Closed** 2019-11-24 00:08 UTC

**Comment by ac31447** [comment] 2019-11-24 00:09
thanks ill try them.
