### ISSUE TITLE
Backpack bug

### ISSUE THREAD

**Issue by LWmods** [Freebi85/Dungeons-Dragons-Space-Shuttles#126] opened 2019-04-22 19:42 UTC
after updating the pack to 4.11 there is an issue with the advanced backpack from v0id's smart backpacks it shows as empty although the items are still there you have to click the first slot of the bag for items to show. it happens every time you open or close it.

edit- after about an hour it seems to have deleted its inventory completely.

**Comment by Freebi85** [comment] 2019-04-23 05:11
Thx  i will look into it. Is this on a server or in a singelplayer world?

**Comment by LWmods** [comment] 2019-04-23 07:24
hey, this is on a server we haven't made any changes its just forge. also, I was talking to a friend it doesn't happen to him while he is wearing the backpack on his back while mine was just in my Hotbar, and in both cases no upgrades were installed to the backpacks. thanks.

**Comment by Freebi85** [comment] 2019-04-23 11:41
apparently these are desync issues with backpacks on servers. (not voided just invisible items sometimes) If you put your backpack on your back, it shouldn't happen. This is of course not a solution but for now as information.

**Comment by Temeriki** [comment] 2019-05-06 16:16
Ive had this bug hit me shortly after updating to 4.11a, the backpack accessed from the hotbar and was truly wiped after a few times just appearing wiped (changing it to back didnt bring the items back) no issues with it on the back.  I was moving between creative and survival at the time so that may of been a component factor.

**Comment by Temeriki** [comment] 2019-05-09 13:32
So some more information, I broke my server by letting my ssd fill up while it was running.  After some creative transplantation of the world and some older character files into a fresh instance I was able to recover the server.  This process included the server thinking it was 4.9a again and giving me the prompt to fml confirm the missing files removed in 4.11a.  The backpack on my chest slot still had all its items in it so it seems the issue is mitigated by wearing the backpack and not accessing it via hotbar, either that or i lucked out with a buggy mod, still havnt lost a backpack inventory since wearing the backpack.  I did have to change my keybindings to be able to wear it though.

**Comment by Freebi85** [comment] 2019-05-09 13:53
Yeah it's a server desync issue and dosen't happen on singleplayer worlds. If you put your backpack on your back, it shouldn't happen anymore. Still waiting for fix.

**Comment by Temeriki** [comment] 2019-05-09 18:00
Was just reiterating that it seems rock solid stable on your back.

**Comment by Dan-Ross** [comment] 2019-08-25 22:54
Any word on a fix, it's been months since first report. If the author isn't fixing this, can a replacement mod be found? Users are complaining the backpacks are eating their items and they're leaving the server.

**Comment by ljcomplex** [comment] 2019-09-05 17:05
Additional issue I have noticed. When I die with the backpack in my inventory, the backpack itself gets deleted, as it is not recovered by picking up my grave. Currently on 5.7b.

**Comment by dierke9** [comment] 2019-09-05 17:26
@ljcomplex take alook if it is equiped. Look in your controls to see what button open the backpack and press that button (if it doesnt open anything make sure that there are no conflicts with other controls)

**Comment by dierke9** [comment] 2019-09-05 17:28
@Dan-Ross as stated above the backpacks arent eating the items they are just invisable due to a desync. I myself has been taking a small look into the mod but havent found the cause of this yet.

**Comment by Dan-Ross** [comment] 2019-09-05 17:31
Yeah, the items are still there, but users don't know they're there and that you have to click in the first empty spot to have them appear again. To the average, non-Github active player, this mod 'eats' the items, so players leave the server.

**Comment by ljcomplex** [comment] 2019-09-05 17:54
@dierke9 Well, I feel dumb now. It is indeed equipped. Thanks!

**Comment by Freebi85** [comment] 2019-09-05 19:16
Yes the desyncs are tedious if you don't equip the backpack on a server. But leaving a server because of a backpack glitch... it's more likely that these people don't like the pack.
Anyway, the bug is supposed to be fixed indev. For some reason it is not updated. I've already hired several people to deal with it and possibly create a fork. There is no guarantee for that. I haven't decided yet if I will replace the mod completely if it doesn't work.

**Comment by Dan-Ross** [comment] 2019-09-05 19:20
@Freebi85 thanks for the reply. I think they like the pack, but I think they hate 'losing' high-effort items. Given the extra difficulty of mobs on the server, most folks so far have been choosing to wear armour instead of the backpack.  

Anyways, thank for looking into the issue, hope they're able to resolve it soon. Personally, I've been loving the pack.

**Comment by dierke9** [comment] 2019-09-05 22:07
But the backpack doesn't use any armor slots? Backpacks have their own hidden "slot"

**Comment by Freebi85** [comment] 2020-01-18 01:19
Removed in 7.0

**Closed by Freebi85** 2020-01-18 01:19 UTC
Labels: Mod Issue, awaiting fix from mod author
