### ISSUE TITLE
Replace inventory tweak with inventory sorter?

### ISSUE THREAD

**Issue by LordHellscream** [Freebi85/Dungeons-Dragons-Space-Shuttles#738] opened 2020-03-01 07:53 UTC
There has been a long existing issues with inventory tweak and refined storage. 
If you press middle button while opening refined storage crafting grid it will completely mess up your inventory and task bar. 
The usual solution is to replace the mod with inventory sorter. I don't mind doing this on my own except that every time there was an update i had to re-do this. 

Also for many players who didn't know about this, it could take them some time to look up solution online and it's not very easy to find this information.

Perhaps it would be good to consider replace this mod for the pack.

thanks for your consideration. 

EDIT: more info:
Refined storage refused to fix it:
https://github.com/raoulvdberge/refinedstorage/issues/2014 
Inventory Tweak refused to fix it:
https://github.com/Inventory-Tweaks/inventory-tweaks/issues/500

**Comment by LordHellscream** [comment] 2020-03-01 22:39
@Landmaster care to explain why a thumb-down?

**Comment by dierke9** [comment] 2020-03-04 17:45
Hello

Would it be possible to provide a link about the issue, that way we can see if there are possible any config settings or so that might resolve the issue

**Comment by LordHellscream** [comment] 2020-03-04 18:52
https://github.com/raoulvdberge/refinedstorage/issues/2014

**Comment by Landmaster** [comment] 2020-03-05 01:17
@LordHellscream 
The best workaround here, as far as I know, is to turn middle click sorting false and change the sort keybind to an obscure character such as backslash.

I strongly disagree with removing Inventory Tweaks, especially as it offers more than just sorting (specifically automatic item replacement), and Inventory Sorter is an inferior mod in every way IMO.

**Comment by LordHellscream** [comment] 2020-03-05 06:36
I disagree. 
You are suggesting a config change that disable the most convenient feature for both mods (that's the middle mouse button sorting). From a usability stand point, having the most used action right at your finger tip is far superior than moving that to a clumsy keyboard shortcut. Especially such an action has become a habit for majority of modded minecraft players.

Your second point of losing the item replacement. this is not as much an issue for this pack as you will have your tinker tool in the first few quests, and also have access to the dank null. How often is item replacement really that useful? 

I actually tried disabling the mid-key sort, and i couldn't play for more than an hour before switching back. and I hardly noticed the missing of item replacement.

Of course if you an AE2 user then it's like this change is not needed for you. But for at least 50% of us RS users this is real pain.

**Comment by Landmaster** [comment] 2020-03-05 20:31
I took a peek at the Inventory Tweaks code, and it seems that they have an API for designating player slots so that stuff works properly with modded containers. I'll see if it's possible to make a PR to Refined Storage to fix this.

**Comment by Landmaster** [comment] 2020-03-05 21:25
@LordHellscream I think I have found the issue. The problem is that Refined Storage adds the hotbar slot first, followed by the other slots, whereas it really should be the other way around. I'll PR to Refined Storage to fix this.

**Comment by Landmaster** [comment] 2020-03-05 21:30
PR to fix is at raoulvdberge/refinedstorage#2447

**Comment by LordHellscream** [comment] 2020-03-05 22:16
I hope RS author will approve the pull request! thanks @Landmaster

**Comment by Freebi85** [comment] 2020-04-27 11:44
Fixed in next version.

**Closed** 2020-05-02 12:27 UTC
Labels: Fixed / Added / Reworked in next Update, awaiting fix from mod author
