### ISSUE TITLE
Smeltery fuel issue - mod interaction.

### ISSUE THREAD

**Issue by DaveB63** [Freebi85/Dungeons-Dragons-Space-Shuttles#295] opened 2019-08-27 22:40 UTC
This is a long-standing issue that I've seen in several packs featuring addons by other mods to Tinkers Construct. While it could be argued that it is an issue with those mods, it's an issue with _a lot_ of them and could be practically addressed at a modpack level.

The issue: Some smeltery fuels do not work - they generate 0 temp since they are not recognized as a valid smeltery fuel even though they are listed as a fuel when reviewing smeltery recipes in JEI 

I've verified this issue is present in DD&SS with liquid magma - it shows up as a possible fuel in JEI, hotter than lava, but does not work in a smeltery. It may be present with other "hotter" fuels also, which is potentially serious as it these hotter fuels are required for high level smeltery recipes.

The cause: mods introducing recipes that require hotter fuels than lava but not registering those fuels with TiCon.

Pack-level fix: create a craftTweaker script as part of the pack that registers the hotter fuels with TiCon using a call to mods.tconstruct.Fuel.registerFuel(ILiquidStack fuel, int duration); for each non-working fuel in the pack.

**Comment by Freebi85** [comment] 2019-08-28 19:01
Well adding the fuel it's not a problem at all. The problem is adding fuels to the smeltery don't have any temperatur values and can't smelt anything -.-

Although Liquid Magma has a temperature of 300K, it has 0 in the Smeltery. When I try to manipulate the temperature by crafttweaker, unfortunately nothing changes for the smeltery. That's probably why it doesn't work in any modpack.

In short, the Tinkers Crafttweaker script is useless without being able to assign a temperature which is not possible.

Maybe I miss something. I will do some more tests.  If it doesn't work we have to move the issue to Tinkers construct.

Translated with www.DeepL.com/Translator

**Comment by DaveB63** [comment] 2019-08-29 11:03
I've done more testing. Here are my observations:
1: every fuel EXCEPT liquid magma works as intended.
2: liquid magma fluid is duplicated
       2.1: Fluid added by Extra Planets: "Liquid Magma"
       2.2: Fluid added by Tinkers Alloying Addon: "Liquid Magma.name" (added second with the .name suffix auto-applied to disambiguate?)
3: Every recipe generates - and uses - the Extra Planets liquid magma but it is not a smeltery fuel
4: Tinkers alloying liquid magma is a smeltery fuel - which is why it shows up as one in JEI - but neither generates nor is it possible to make it.
5: using creative mode, the Tinkers Alloying liquid magma can be placed in the world. It cannot be picked up. trying to fill a bucket results in the consumption of the source block and an empty bucket

So I was wrong about the cause of the issue - its that the two mods both add the fluid but they are not equivalent. The Extra planets

**Comment by DaveB63** [comment] 2019-08-29 18:28
on reflection, as a result of my previous observations, I would question the "mod issue" tag - as this is a conflict _between two mods_ - it is reasonable to assume that the authors of the respective mods might decline to address it, each in favor of the other one handling it. One would hope that is not the case but it is a very possible outcome.

**Comment by Freebi85** [comment] 2019-09-18 05:31
It looks like the Tinker Alloying Magma isn't finished in the mod and it never will be because the project was abandoned :/ There's no way for me to remove a fuel type, so if I can't get the extra planets fluid to work (which has failed so far) I'll have to close this as unresolved. Except Extra Planets adds this fluid as valid smeltery fluid which I doubt.

**Closed** 2019-12-15 12:01 UTC
Labels: Mod Issue, can't fix :(
