### ISSUE TITLE
Actually Additions batteries automating

### ISSUE THREAD

**Issue by ray73864** [Freebi85/Dungeons-Dragons-Space-Shuttles#542] opened 2019-12-13 06:08 UTC
Manually crafting or automating the crafting of Actually Additions batteries beyond the single ones seems temperamental at best.

The single is easy since it doesn't rely on an existing battery, the double, triple and quadruple however seem to have issues.

Right now I have an RS pattern set up to create the double battery, I made sure that the single battery it requires was a non-charged non-baubles one.

When I search RS for 'battery' and then hover over the single battery, I can see that it makes a 0/200,000 Crystal Flux battery, when I look at the pattern for the double battery, I can see that everything appears to match with regards to the required single battery, but when I tell RS to craft it, it says it is missing a single battery.

Running 6.5 of the modpack.

**Comment by Freebi85** [comment] 2019-12-13 06:46
The Problem is the Carpenter dosen't support shift-clicking or automating AA batterys with crafters because they always need to be put manually into it. At least for the first recipe. The machine have too many problems to recognize the NBT Data. The single one isn't a problem because you don't need another batrttery for it. 

I was against an implementation of this in the carpenter because I knew it would be a problem.
But the community still wanted it as an alternative to the workshop. Probably I have to change the entire crafting system and let convert the batteries first to "upgrades kits" like the exchangers if you know what I mean.

**Comment by ray73864** [comment] 2019-12-13 07:32
Ahh ok, that makes sense. How about an extended crafting recipe using the advanced crafting table? 

It would require something to make it still cost the same as doing it via the carpenter, maybe charge 2 single batteries? I mean, 'double' suggests that it requires 2 singles to make.

Or would the advanced crafting tables have the same issue as the carpenter?

**Comment by PatrickZergRush** [comment] 2019-12-14 09:02
Ray, I have been experiencing similar problems and I believe I found a solution. If you press the advanced tooltip hotkey combo (f3+H, i believe) you'll see that sometimes the batteries have a random nbt tag. check that your double, triple, and quad don't have that tag (cycle it through your crafting grid). If the recipe isn't looking for that tag, idk what the tag actually is, it will craft a lot smoother. When you get to the actual carpenter part, use jei to put the recipe into the carpenter. Then simply drag one of the empty batteries that RS/AE2 puts in the carpenter in that spot. Works like a charm

**Comment by ben-mkiv** [comment] 2020-01-04 15:02
the NBT changes once they get charged a bit. You should be able to fix the carpenter recipe by manually placing a crafted uncharged battery in the first recipe slot, that way it should recognize the batteries which get placed in the machine input

**Comment by ray73864** [comment] 2020-01-04 21:07
> the NBT changes once they get charged a bit. You should be able to fix the carpenter recipe by manually placing a crafted uncharged battery in the first recipe slot, that way it should recognize the batteries which get placed in the machine input

Except that the recipe was built using JEI's '+' button, so that shouldn't have any affect on it I would have thought.

**Comment by LordHellscream** [comment] 2020-02-18 08:58
I am beginning to experience this issue as well. It would be great to subtitute the AA batteries in the recipe with something else. it's quite painful for autocrafting.

**Comment by Freebi85** [comment] 2020-02-20 16:38
merged to https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/701 😃

**Closed by Freebi85** 2020-02-20 16:38 UTC
Labels: Is currently under investigation
