### ISSUE TITLE
Starlight Infuser Multiblock not working

### ISSUE THREAD

**Issue by Elijah0331** [Freebi85/Dungeons-Dragons-Space-Shuttles#231] opened 2019-07-23 02:29 UTC
I crafted the Starlight Infuser and assembled to multiblock structure properly. Had 2 other people confirm it was done properly and still it will not function. Anyone else had this issue or know why it wouldn't be working? Thanks!

**Comment by Freebi85** [comment] 2019-07-23 04:17
I can't change the way how Multiblocks in Astral sorcery works. 
Try on a singleplayer world if this happens again. 

Also, you have Tome progression for the infuser, correct? The infusions are gated like everything is Astral Sorcery.

It is important that you crafted everything yourself in astral sorcery because the progress is bound to the player. For example, you can't use a luminious crafting table if it was made by another player and you don't have one yet.

**Comment by Elijah0331** [comment] 2019-07-23 18:43
I completed all of the White Magic Tier 1 and 2 quests and I crafted all of it myself. I will try it in a single player server and see if it changes anything.

**Comment by Elijah0331** [comment] 2019-07-23 18:57
Tested on a single player server and still no luck getting the structure to function either.

**Comment by cyber01** [comment] 2019-07-23 19:47
Many opportunities in Astral open only after certain actions in the book Astral. Maybe just creating blocks is not enough.

**Comment by Freebi85** [comment] 2019-09-01 18:02
Is this still a thing? I can't reproduce an issue with the multiblock.

**Comment by weightmaker** [comment] 2019-09-03 11:25
i assume he used the Underground Biome's marble instead of Astral for the "clean" looking ones. thats a common mistake i've seen people do. Astral multiblocks doesnt do oredict so you need to use the exact blocks it sais it needs. 
Anyway im pretty sure it a user error.

**Comment by Freebi85** [comment] 2019-09-05 18:24
That's what I'm assuming, too. I'm closing here because there are no more informations and I personally can't reproduce the issue on 5.7b.

**Closed by Freebi85** 2019-09-05 18:24 UTC
Labels: Can't Reproduce
